### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by ad9311** [ad9311/space-travelers-hub#25]
## Greetings! 👋🏽 

This is our [Project Link](https://github.com/ad9311/space-travelers-hub). We are two people @ad9311 and @Ntwali-Josue

**Comment by Davidosky007** [comment]
## Hi @ad9311 @Ntwali-Josue 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, with a broken link to GitHub project kindly provide a link that leads to github project 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ad9311** [comment]
The Microverse dashboard requires me to submit an issues link.

**Comment by BrianSammit** [comment]
# STATUS: APROVED :green_circle: :clap: 

Hello @ad9311 @Ntwali-Josue , 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
